[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && npm run db:migrate && npm run db:seed:all && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
